# Generated by Django 3.0.1 on 2020-01-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200106_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
