# Generated by Django 3.0.1 on 2020-01-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200111_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='public',
        ),
    ]
