# Generated by Django 3.0.1 on 2020-01-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_album_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_thumnbails'),
        ),
    ]
