# Generated by Django 3.0.1 on 2020-01-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_auto_20200111_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='my_image',
            new_name='album_cover',
        ),
    ]
