# Generated by Django 3.0.1 on 2020-01-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20200114_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
