# Generated by Django 3.0.1 on 2020-01-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
